=== Mikalai88/javatask1/dataxml/TouristVouchers.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
        targetNamespace="TouristVouchers.xsd"
        xmlns:tns="TouristVouchers.xsd" elementFormDefault="qualified">

    <element name="TouristVouchers">
        <complexType>
            <sequence>
                <element name="voucher" maxOccurs="unbounded">
                    <complexType>
                        <sequence>
                            <element name="type" type="tns:Type"/>
                            <element name="country" type="string"/>
                            <element name="daysNights" type="tns:DaysNightsType"/>
                            <element name="issueDate" type="dateTime"/>
                            <element name="transport" type="tns:Transport"/>
                            <element name="hotel" type="tns:ExtendedHotelCharacteristic"/>
                            <element name="cost" type="decimal"/>
                        </sequence>
                        <attribute name="id" type="ID" use="required"/>
                    </complexType>
                </element>
            </sequence>
        </complexType>
    </element>

    <simpleType name="Type">
        <restriction base="string">
            <enumeration value="weekend"/>
            <enumeration value="excursion"/>
            <enumeration value="recreation"/>
            <enumeration value="pilgrimage"/>
        </restriction>
    </simpleType>

    <simpleType name="Transport">
        <restriction base="string">
            <enumeration value="air"/>
            <enumeration value="rail"/>
            <enumeration value="auto"/>
            <enumeration value="liner"/>
        </restriction>
    </simpleType>

    <simpleType name="Meal">
        <restriction base="string">
            <enumeration value="HB"/>
            <enumeration value="BB"/>
            <enumeration value="Al"/>
        </restriction>
    </simpleType>

    <complexType name="HotelCharacteristic">
        <sequence>
            <element name="stars" type="int"/>
            <element name="mealIncluded" type="boolean"/>
            <element name="mealType" type="tns:Meal" default="BB"/>
            <element name="roomType" type="string"/>
            <element name="tvIncluded" type="boolean"/>
            <element name="acIncluded" type="boolean"/>
        </sequence>
    </complexType>

    <complexType name="ExtendedHotelCharacteristic">
        <complexContent>
            <extension base="tns:HotelCharacteristic">
                <sequence>
                    <element name="wifiIncluded" type="boolean"/>
                </sequence>
            </extension>
        </complexContent>
    </complexType>

    <simpleType name="DaysNightsType">
        <restriction base="string">
            <pattern value="\d+/\d+"/>
        </restriction>
    </simpleType>
</schema>

=== Mikalai88/javatask1/dataxml/TouristVouchers.xml
<?xml version="1.0"?>
<TouristVouchers xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="TouristVouchers.xsd"
                 xsi:noNamespaceSchemaLocation="TouristVouchers.xsd">
    <voucher id="v1">
        <type>excursion</type>
        <country>Italy</country>
        <daysNights>5/4</daysNights>
        <issueDate>2024-04-01T15:00:00Z</issueDate>
        <transport>air</transport>
        <hotel>
            <stars>5</stars>
            <mealIncluded>true</mealIncluded>
            <mealType>Al</mealType>
            <roomType>double</roomType>
            <tvIncluded>true</tvIncluded>
            <acIncluded>true</acIncluded>
            <wifiIncluded>true</wifiIncluded>
        </hotel>
        <cost>1500.00</cost>
    </voucher>
    <voucher id="v2">
        <type>weekend</type>
        <country>Italy</country>
        <daysNights>2/1</daysNights>
        <issueDate>2024-05-01T15:00:00Z</issueDate>
        <transport>auto</transport>
        <hotel>
            <stars>4</stars>
            <mealIncluded>false</mealIncluded>
            <roomType>double</roomType>
            <tvIncluded>false</tvIncluded>
            <acIncluded>true</acIncluded>
            <wifiIncluded>true</wifiIncluded>
        </hotel>
        <cost>250.00</cost>
    </voucher>
    <voucher id="v3">
        <type>excursion</type>
        <country>France</country>
        <daysNights>5/4</daysNights>
        <issueDate>2024-03-01T15:00:00Z</issueDate>
        <transport>rail</transport>
        <hotel>
            <stars>3</stars>
            <mealIncluded>true</mealIncluded>
            <mealType>BB</mealType>
            <roomType>single</roomType>
            <tvIncluded>true</tvIncluded>
            <acIncluded>false</acIncluded>
            <wifiIncluded>true</wifiIncluded>
        </hotel>
        <cost>1000.00</cost>
    </voucher>
    <voucher id="v4">
        <type>recreation</type>
        <country>Austria</country>
        <daysNights>7/6</daysNights>
        <issueDate>2024-02-01T15:00:00Z</issueDate>
        <transport>auto</transport>
        <hotel>
            <stars>3</stars>
            <mealIncluded>true</mealIncluded>
            <mealType>HB</mealType>
            <roomType>double</roomType>
            <tvIncluded>true</tvIncluded>
            <acIncluded>true</acIncluded>
            <wifiIncluded>true</wifiIncluded>
        </hotel>
        <cost>1400.00</cost>
    </voucher>
    <voucher id="v5">
        <type>pilgrimage</type>
        <country>Spain</country>
        <daysNights>15/14</daysNights>
        <issueDate>2024-01-01T15:00:00Z</issueDate>
        <transport>rail</transport>
        <hotel>
            <stars>2</stars>
            <mealIncluded>false</mealIncluded>
            <roomType>double</roomType>
            <tvIncluded>false</tvIncluded>
            <acIncluded>false</acIncluded>
            <wifiIncluded>false</wifiIncluded>
        </hotel>
        <cost>800.00</cost>
    </voucher>
    <voucher id="v6">
        <type>weekend</type>
        <country>Italy</country>
        <daysNights>1/2</daysNights>
        <issueDate>2024-04-02T15:00:00Z</issueDate>
        <transport>liner</transport>
        <hotel>
            <stars>5</stars>
            <mealIncluded>true</mealIncluded>
            <mealType>Al</mealType>
            <roomType>single</roomType>
            <tvIncluded>true</tvIncluded>
            <acIncluded>true</acIncluded>
            <wifiIncluded>true</wifiIncluded>
        </hotel>
        <cost>1700.00</cost>
    </voucher>
    <voucher id="v7">
        <type>excursion</type>
        <country>Italy</country>
        <daysNights>5/4</daysNights>
        <issueDate>2024-04-03T15:00:00Z</issueDate>
        <transport>air</transport>
        <hotel>
            <stars>5</stars>
            <mealIncluded>true</mealIncluded>
            <mealType>Al</mealType>
            <roomType>double</roomType>
            <tvIncluded>true</tvIncluded>
            <acIncluded>true</acIncluded>
            <wifiIncluded>true</wifiIncluded>
        </hotel>
        <cost>1500.00</cost>
    </voucher>
    <voucher id="v8">
        <type>excursion</type>
        <country>Italy</country>
        <daysNights>5/4</daysNights>
        <issueDate>2024-04-01T15:10:00Z</issueDate>
        <transport>air</transport>
        <hotel>
            <stars>5</stars>
            <mealIncluded>true</mealIncluded>
            <mealType>Al</mealType>
            <roomType>double</roomType>
            <tvIncluded>true</tvIncluded>
            <acIncluded>true</acIncluded>
            <wifiIncluded>true</wifiIncluded>
        </hotel>
        <cost>1500.00</cost>
    </voucher>
    <voucher id="v9">
        <type>excursion</type>
        <country>Italy</country>
        <daysNights>5/4</daysNights>
        <issueDate>2024-04-01T15:01:00Z</issueDate>
        <transport>air</transport>
        <hotel>
            <stars>5</stars>
            <mealIncluded>true</mealIncluded>
            <mealType>Al</mealType>
            <roomType>double</roomType>
            <tvIncluded>true</tvIncluded>
            <acIncluded>true</acIncluded>
            <wifiIncluded>true</wifiIncluded>
        </hotel>
        <cost>1500.00</cost>
    </voucher>
    <voucher id="v10">
        <type>excursion</type>
        <country>Italy</country>
        <daysNights>5/4</daysNights>
        <issueDate>2024-04-01T15:20:00Z</issueDate>
        <transport>air</transport>
        <hotel>
            <stars>5</stars>
            <mealIncluded>true</mealIncluded>
            <mealType>Al</mealType>
            <roomType>double</roomType>
            <tvIncluded>true</tvIncluded>
            <acIncluded>true</acIncluded>
            <wifiIncluded>true</wifiIncluded>
        </hotel>
        <cost>1500.00</cost>
    </voucher>
    <voucher id="v11">
        <type>excursion</type>
        <country>Italy</country>
        <daysNights>5/4</daysNights>
        <issueDate>2024-03-01T17:00:00Z</issueDate>
        <transport>air</transport>
        <hotel>
            <stars>5</stars>
            <mealIncluded>true</mealIncluded>
            <mealType>Al</mealType>
            <roomType>double</roomType>
            <tvIncluded>true</tvIncluded>
            <acIncluded>true</acIncluded>
            <wifiIncluded>true</wifiIncluded>
        </hotel>
        <cost>1500.00</cost>
    </voucher>
    <voucher id="v12">
        <type>excursion</type>
        <country>Italy</country>
        <daysNights>5/4</daysNights>
        <issueDate>2024-04-01T15:00:20Z</issueDate>
        <transport>air</transport>
        <hotel>
            <stars>5</stars>
            <mealIncluded>true</mealIncluded>
            <mealType>Al</mealType>
            <roomType>double</roomType>
            <tvIncluded>true</tvIncluded>
            <acIncluded>true</acIncluded>
            <wifiIncluded>true</wifiIncluded>
        </hotel>
        <cost>1500.00</cost>
    </voucher>
    <voucher id="v13">
        <type>excursion</type>
        <country>Italy</country>
        <daysNights>5/4</daysNights>
        <issueDate>2024-04-01T15:00:00Z</issueDate>
        <transport>air</transport>
        <hotel>
            <stars>5</stars>
            <mealIncluded>true</mealIncluded>
            <mealType>Al</mealType>
            <roomType>double</roomType>
            <tvIncluded>true</tvIncluded>
            <acIncluded>true</acIncluded>
            <wifiIncluded>true</wifiIncluded>
        </hotel>
        <cost>1500.00</cost>
    </voucher>
    <voucher id="v14">
        <type>excursion</type>
        <country>Italy</country>
        <daysNights>5/4</daysNights>
        <issueDate>2024-04-01T15:00:00Z</issueDate>
        <transport>air</transport>
        <hotel>
            <stars>5</stars>
            <mealIncluded>true</mealIncluded>
            <mealType>Al</mealType>
            <roomType>double</roomType>
            <tvIncluded>true</tvIncluded>
            <acIncluded>true</acIncluded>
            <wifiIncluded>true</wifiIncluded>
        </hotel>
        <cost>1500.00</cost>
    </voucher>
    <voucher id="v15">
        <type>excursion</type>
        <country>Italy</country>
        <daysNights>5/4</daysNights>
        <issueDate>2024-04-01T15:00:00Z</issueDate>
        <transport>air</transport>
        <hotel>
            <stars>5</stars>
            <mealIncluded>true</mealIncluded>
            <mealType>Al</mealType>
            <roomType>double</roomType>
            <tvIncluded>true</tvIncluded>
            <acIncluded>true</acIncluded>
            <wifiIncluded>true</wifiIncluded>
        </hotel>
        <cost>1500.00</cost>
    </voucher>
    <voucher id="v16">
        <type>excursion</type>
        <country>Italy</country>
        <daysNights>5/4</daysNights>
        <issueDate>2024-04-01T15:00:00Z</issueDate>
        <transport>air</transport>
        <hotel>
            <stars>5</stars>
            <mealIncluded>true</mealIncluded>
            <mealType>Al</mealType>
            <roomType>double</roomType>
            <tvIncluded>true</tvIncluded>
            <acIncluded>true</acIncluded>
            <wifiIncluded>true</wifiIncluded>
        </hotel>
        <cost>1500.00</cost>
    </voucher>
</TouristVouchers>
